using UnityEngine;

namespace UitkForKsp2.API;

/// <summary>
/// Options for creating a window.
/// </summary>
[PublicAPI]
public struct WindowOptions
{
    /// <summary>
    /// Unique ID for the game object. Autogenerated if null.
    /// </summary>
    public string? WindowId { get; set; }

    /// <summary>
    /// Parent game object transform. Uses "UI Manager(Clone)/Main Canvas" if null.
    /// </summary>
    public Transform? Parent { get; set; }

    /// <summary>
    /// Should window hiding with F2 be enabled?
    /// </summary>
    public bool IsHidingEnabled { get; set; }

    /// <summary>
    /// Should it use the UI scale setting?
    /// </summary>
    public bool UseStockScale { get; set; }

    /// <summary>
    /// Should the game input be disabled when a text field is focused? This will only affect text fields
    /// </summary>
    public bool DisableGameInputForTextFields { get; set; }

    /// <summary>
    /// Should the window be brought to front when clicked?
    /// </summary>
    public bool BringToFrontOnPointerDown { get; set; }

    /// <summary>
    /// Should pointer and wheel input over this window block gameplay input?
    /// </summary>
    public bool BlockGameInput { get; set; }

    /// <summary>
    /// Options for moving the window by dragging.
    /// </summary>
    public MoveOptions MoveOptions { get; set; }

    /// <summary>
    /// Options for resizing the window from the lower-right corner.
    /// </summary>
    public ResizeOptions ResizeOptions { get; set; }

    /// <summary>
    /// Default options for creating a window.
    /// </summary>
    public static WindowOptions Default => new()
    {
        WindowId = null,
        Parent = null,
        IsHidingEnabled = true,
        UseStockScale = true,
        DisableGameInputForTextFields = true,
        BringToFrontOnPointerDown = true,
        BlockGameInput = true,
        MoveOptions = MoveOptions.Default,
        ResizeOptions = ResizeOptions.Default
    };
}
