using UnityEngine;

namespace UitkForKsp2.API;

/// <summary>
/// Options for creating a window.
/// </summary>
public struct WindowOptions
{
    /// <summary>
    /// Unique ID for the game object. Autogenerated if null.
    /// </summary>
    public string WindowId { get; set; }

    /// <summary>
    /// Parent game object transform. Uses "UI Manager(Clone)/Main Canvas" if null.
    /// </summary>
    public Transform Parent { get; set; }

    /// <summary>
    /// Should window hiding with F2 be enabled?
    /// </summary>
    public bool IsHidingEnabled { get; set; }

    /// <summary>
    /// Options for moving the window by dragging.
    /// </summary>
    public MoveOptions MoveOptions { get; set; }

    /// <summary>
    /// Default options for creating a window.
    /// </summary>
    public static WindowOptions Default => new()
    {
        WindowId = null,
        Parent = null,
        IsHidingEnabled = true,
        MoveOptions = MoveOptions.Default
    };
}