name: KSP Builder

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: KSP2 Builder
        uses: Rexicon226/KSP2Builder@V0.1
